services:
  - type: web
    name: learnenglish-chat-twinterrordark
    runtime: node
    plan: free
    region: frankfurt
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
